server:
  port: 8080
  servlet.context-path: /

spring:
  http.encoding.charset: UTF-8
  messages.encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        user_sql_comments: true
        format_sql: true
        jdbc_lob_contextual_creation: true
        order_by.default_null_ordering: last
        type: trace
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    default-property-inclusion: non_null
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver

swagger.api:
  title: JIM
  description: JIM application
