DROP TABLE IF EXISTS competition_price;
DROP TABLE IF EXISTS competition_distance;
DROP TABLE IF EXISTS championship_type;
DROP TABLE IF EXISTS competition;

CREATE TABLE competition (
  ID MEDIUMINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR (255) NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP DEFAULT NULL,
  DESCRIPTION TEXT NOT NULL,
  ADDRESS VARCHAR (255) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (255) NOT NULL,
  MODIFIED TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR (255) NOT NULL
);

ALTER TABLE competition ADD CONSTRAINT pk_comp PRIMARY KEY (ID);

CREATE TABLE championship_type (
  ID MEDIUMINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR (255) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (255) NOT NULL,
  MODIFIED TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR (255) NOT NULL
);

ALTER TABLE championship_type ADD CONSTRAINT pk_champ_type PRIMARY KEY (ID);

CREATE TABLE competition_distance (
  ID MEDIUMINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR (255) NOT NULL,
  LENGTH DECIMAL DEFAULT NULL,
  CHAMPIONSHIP_TYPE_ID MEDIUMINT DEFAULT NULL,
  SPECIAL_NOTES TEXT,
  COMPETITION_ID MEDIUMINT NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  START_NUMBERING INTEGER DEFAULT NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (255) NOT NULL,
  MODIFIED TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR (255) NOT NULL
);

ALTER TABLE competition_distance ADD CONSTRAINT pk_comp_dist PRIMARY KEY (ID);
ALTER TABLE competition_distance
  ADD CONSTRAINT fk_champ_type_id FOREIGN KEY(CHAMPIONSHIP_TYPE_ID) REFERENCES championship_type(ID);
ALTER TABLE competition_distance
  ADD CONSTRAINT fk_comp_id FOREIGN KEY(COMPETITION_ID) REFERENCES competition(ID);

CREATE TABLE competition_price (
  ID MEDIUMINT AUTO_INCREMENT NOT NULL,
  COMPETITION_DISTANCE_ID MEDIUMINT NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE DECIMAL DEFAULT NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (255) NOT NULL,
  MODIFIED TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR (255) NOT NULL
);

ALTER TABLE competition_price ADD CONSTRAINT pk_comp_price PRIMARY KEY (ID);
ALTER TABLE competition_price
  ADD CONSTRAINT fk_comp_dist_id FOREIGN KEY(COMPETITION_DISTANCE_ID) REFERENCES competition_distance(id);
